### ISSUE TITLE
declare compatible firefox versions

### ISSUE THREAD

**Issue by ewen-lbh** [ewen-lbh/ffcss#13]
add new key:

```yaml
ffcss: 1

...

firefox: 89+

...
```

add + at the end to mean ...and up. no dot means .0.
