### ISSUE TITLE
Change files depending on firefox version

### ISSUE THREAD

**Issue by ewen-lbh** [ewen-lbh/ffcss#15]
Something like `variant` but for `firefox`:

```yaml

firefox:
  nightly:
    repositry: https://github.com/Guerra24/Firefox-UWP-Style/archive/refs/heads/master.zip
  89-90:
    repository: https://github.com/Guerra24/Firefox-UWP-Style/archive/refs/heads/firefox-89.zip
  88:
    repository: https://github.com/Guerra24/Firefox-UWP-Style/archive/refs/heads/firefox-88.zip
  76-87:
    repository: https://github.com/Guerra24/Firefox-UWP-Style/archive/refs/heads/firefox-76.zip
```

Now `firefox: <number or string>` will need to be transformed before unmarshaling to:

```yaml
firefox:
  <number or string>: {}
```

To get the compatible firefox versions, just  `firefox`'s keys as OR patterns.

By the way, we got support OR patterns with `firefox: [53-65, 89+]` (that gets expanded to `firefox: [53-65: {}, 89+: {}]` before unmarshaling)
