### ISSUE TITLE
Specify the branch to clone

### ISSUE THREAD

**Issue by ewen-lbh** [ewen-lbh/ffcss#25]
Add `branch` to the manifest:

```yaml

...

branch: branch-name-to-clone

...
```

The branch defaults to the repo's default branch: it just gets cloned without `--branch` set.

Use-case: https://github.com/black7375/Firefox-UI-Fix (for the Photon-style variant):

```yaml

variants:
  photon-style:
    branch: photon-style
```
