### ISSUE TITLE
run custom pre/post-install scripts

### ISSUE THREAD

**Issue by ewen-lbh** [ewen-lbh/ffcss#40]
add:

```yaml
run:
  before: ...
  after: ...
```

Make `{{ profile_dir }}` available to both `before` and `after`, and will be replaced with the chosen profile directory (the script(s) will run for every profile chosen by the user)
