### ISSUE TITLE
rename os value

### ISSUE THREAD

**Issue by ewen-lbh** [ewen-lbh/ffcss#6]
Useful if e.g. linux & macos use the same folder, or if you use different capitalization (e.g. simplerentfox).

The new config key `os` maps ffcss' values (`windows`, `linux` and `macos`) to values chosen, those new values will be used for `{{ os }}`.

Example, for simplerentfox:

```yaml
os:
  linux: Linux
  macos: Linux
  windows: Windows
```
